### ISSUE TITLE
Signing a passbook

### ISSUE THREAD

**Issue by RayKahn** [assaf/node-passbook#14]
I am getting the following exception:  Signature is missing
How do I sign a passbook?

**Comment by yozef** [comment]
@RayKahn Can you please clarify, as I am receiving the same error:
` The passTypeIdentifier or teamIdentifier provided may not match your certificate, or the certificate trust chain could not be verified.`

If I'm not mistaken, the Team ID is the one you get from here https://developer.apple.com/account/#/membership/

In the Team ID row. Am I missing something?
