### ISSUE TITLE
Publish version 2.0.3 to public npm registry

### ISSUE THREAD

**Issue by AndrewBarba** [assaf/node-passbook#28]
Can we please publish the latest version to npm? Thanks!

**Comment by AndrewBarba** [comment]
Any updates on this? There are valuable fixes in 2.0.3

**Comment by assaf** [comment]
Current status: tests are failing, CHANGELOG/docs not updated to reflect changes.

**Comment by AndrewBarba** [comment]
See https://github.com/assaf/node-passbook/pull/29
