### ISSUE TITLE
WWDR certificate expired Feb 14, 2016

### ISSUE THREAD

**Issue by yozef** [assaf/node-passbook#51]
I am getting issues with signing my pass with this node module.

~~~
Invalid data error reading pass pass.com.xxx.yyy/123456. The passTypeIdentifier or teamIdentifier provided may not match your certificate, or the certificate trust chain could not be verified.
~~~

I am pretty sure it has to do with the expired WWDR certificate this module is using.
The new certificate can be found here: https://developer.apple.com/support/certificates/expiration/

**Current Solution:**
Export the wwdr file downloaded from here: https://developer.apple.com/certificationauthority/AppleWWDRCA.cer into a .pem file from within your Keychain, and place it within the same folder as the other pem file of the pass certificate.

**Comment by assaf** [comment]
This module doesn't bundle any certificates, they are all user supplied.

**Comment by yozef** [comment]
when calling: `node-passbook prepare-keys -p keys` it fetches an older wwdr file.

**Comment by assaf** [comment]
It fetches whatever certificate you have previously loaded into your keychain.
