### ISSUE TITLE
No 'data' event emitted.

### ISSUE THREAD

**Issue by netnacool** [assaf/node-passbook#53]
Hi
Instead of writing the passbook to a file, I wanted it to be stored in memory as a buffer. So, I would have to catch the data events and push it to buffer. But I don't see that the 'data' event is supported in the current implementation.
On going through pass.js, I could only find implementation of the pipe function and no place where data events are emitted.
I might be wrong in my observations, please correct me if that is the case.
If not, then it would be really helpful if support for this could be added.

Thanks,
Nakul

**Comment by assaf** [comment]
The API allows you to pipe into a stream. Your stream can do whatever you want it to.

**Comment by netnacool** [comment]
Ok, I think I can implement a writable stream and override the write method, to write to my buffer.
